
battery:
  soc_min: 0.2 # da modificare in soe_min
  soc_max: 0.8 # da modificare in soe_max
  capacity: 51.2        # [kWh]  
  power_max: 8         # [kW]
  efficiency: 0.9
  init_soc: 0.6 # da modificare in init_soe
  sample_time: 0.25     # [h]
  chemistry: LFP        # Seleziona la chimica della batteria (es. LFP, NMC, NCA)
  # In alternativa è possibile specificare direttamente il modello di transizione UNIPI
  # transition_model: !LfpTransitionModel {}

grid:
  max_import_power: 8   # [kW]
  max_export_power: 8   # [kW]
  prices: [0.15, 0.05, 0.0, 0.0]

ems:
  kafka_topic: test_topic_661
  buffer_size: 96
  timezone: America/Chicago
  steps: 960 
  allow_night_grid_charge: false   # Carica da rete esclusivamente in fascia off-peak

  price_bands:
    peak:
      buy: 0.35
      sell: 0.12
      ranges:
        - [18, 20]
    standard:
      buy: 0.28
      sell: 0.10
      ranges:
        - [7, 17]
        - [21, 22]
    offpeak:
      buy: 0.20
      sell: 0.08
