
battery:
  capacity: 51.2        # [kWh]  
  power_max: 20          # [kW]
  efficiency: 0.9
  init_charge: 20     # [kWh] 
  sample_time: 0.25     # [h]
  state_of_health: 1   # [0-1] Stato di salute della batteria (1.0 = piena salute). Viene automaticamente applicato al modello di transizione.
  chemistry: NMC        # Seleziona la chimica della batteria (es. LFP, NMC, NCA, None)
  # ALTERNATIVA: specificare il modello di transizione UNIPI direttamente (ignora il parametro state_of_health se present)
  # transition_model: !LfpTransitionModel {}
  # transition_model: !NmcTransitionModel {}
  # transition_model: !NcaTransitionModel {} 

grid:
  max_import_power: 8   # [kW]
  max_export_power: 8   # [kW]
  prices: [0.15, 0.05, 0.0, 0.0]

ems:
  kafka_topic: test_topic_661
  buffer_size: 96
  timezone: America/Chicago
  steps: 960
  allow_night_grid_charge: false   # Carica da rete esclusivamente in fascia off-peak

  price_bands:
    peak:
      buy: 0.35
      sell: 0.12
      ranges:
        - [18, 20]
    standard:
      buy: 0.28
      sell: 0.10
      ranges:
        - [7, 17]
        - [21, 22]
    offpeak:
      buy: 0.20
      sell: 0.08
